Check C# files' format by using dotnet-format before commit

diff --git a/.script/pre-commit b/.script/pre-commit
--- a/.script/pre-commit
+++ b/.script/pre-commit
@@ -7,6 +7,9 @@
 #
 # To enable this hook, rename this file to "pre-commit".
 
+fail="echo \"\npre-commit hook failed.\"  >&2 ; exit 1;"
+# fail="printf \"\n\033[31m%s\033[m\n\" \"pre-commit hook failed.\"  >&2 ; exit 1;"
+
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
 	against=HEAD
@@ -19,7 +22,7 @@ fi
 allownonascii=$(git config --type=bool hooks.allownonascii)
 
 # Redirect output to stderr.
-exec 1>&2
+# exec 1>&2
 
 # Cross platform projects tend to avoid non-ASCII filenames; prevent
 # them from being added to the repository. We exploit the fact that the
@@ -46,7 +49,7 @@ EOF
 fi
 
 # If there are whitespace errors, print the offending file names and fail.
-exec git diff-index --check --cached $against --
+# exec git diff-index --check --cached $against --
 
 # Check if pre-commit is up-to-date.
 #
@@ -71,8 +74,25 @@ exec git diff-index --check --cached $against --
 #   exit 1
 # fi
 
-# Format C# scripts by Reshaper
-cleanupcode.sh --include="Assets/Scripts/**/*" --profile="Reformat" UnityTemplate.sln
+# Format C# scripts by Reshaper.
+#
+# echo "Formatting files..."
+# SOLUTION_FILE=$(find . -type f -name "*.sln")
+#
+# if [[ "$OSTYPE" == "msys"* ] -o [ "$OSTYPE" == "cygwin" ]]; then
+#     # For Windows
+#     cleanupcode.exe --include="Assets/Scripts/**/*" --profile="Reformat" UnityTemplate.sln
+# else
+#     cleanupcode.sh --include="Assets/Scripts/**/*" --profile="Reformat" UnityTemplate.sln
+# fi
+#
+# echo "Restaging files: $STAGED_FILES"
+# echo ${STAGED_FILES} | xargs -t -l git add
 
-# Format C# scripts by dotnet-format. editorconfig
-dotnet-format UnityTemplate.sln --include "Assets/Scripts/**/*.cs"
+# Format C# scripts by dotnet-format(See also .editorconfig).
+echo "Check if C# scripts are formatted..."
+dotnet_format_cmd_path=~/.dotnet/tools/dotnet-format
+$dotnet_format_cmd_path -v q --check UnityTemplate.sln --include "Assets/Scripts/**/*.cs" \
+|| (echo "\nC# scripts format error. Please format inappropriate files (see also .editorconfig)." >&2 ; eval $fail)
+
+echo "pre-commit hook finished."
